/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* RED */
#define RED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_0_INBUF_ENABLED 0u
#define RED_0_INIT_DRIVESTATE 0u
#define RED_0_INIT_MUXSEL 0u
#define RED_0_INPUT_SYNC 2u
#define RED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_0_NUM 3u
#define RED_0_PORT GPIO_PRT0
#define RED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_INBUF_ENABLED 0u
#define RED_INIT_DRIVESTATE 0u
#define RED_INIT_MUXSEL 0u
#define RED_INPUT_SYNC 2u
#define RED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_NUM 3u
#define RED_PORT GPIO_PRT0
#define RED_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
