/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* red */
#define red_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define red_0_INBUF_ENABLED 0u
#define red_0_INIT_DRIVESTATE 1u
#define red_0_INIT_MUXSEL 0u
#define red_0_INPUT_SYNC 2u
#define red_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define red_0_NUM 3u
#define red_0_PORT GPIO_PRT0
#define red_0_SLEWRATE CY_GPIO_SLEW_FAST
#define red_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define red_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define red_INBUF_ENABLED 0u
#define red_INIT_DRIVESTATE 1u
#define red_INIT_MUXSEL 0u
#define red_INPUT_SYNC 2u
#define red_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define red_NUM 3u
#define red_PORT GPIO_PRT0
#define red_SLEWRATE CY_GPIO_SLEW_FAST
#define red_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* blue */
#define blue_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define blue_0_INBUF_ENABLED 0u
#define blue_0_INIT_DRIVESTATE 1u
#define blue_0_INIT_MUXSEL 0u
#define blue_0_INPUT_SYNC 2u
#define blue_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define blue_0_NUM 1u
#define blue_0_PORT GPIO_PRT11
#define blue_0_SLEWRATE CY_GPIO_SLEW_FAST
#define blue_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define blue_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define blue_INBUF_ENABLED 0u
#define blue_INIT_DRIVESTATE 1u
#define blue_INIT_MUXSEL 0u
#define blue_INPUT_SYNC 2u
#define blue_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define blue_NUM 1u
#define blue_PORT GPIO_PRT11
#define blue_SLEWRATE CY_GPIO_SLEW_FAST
#define blue_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* led9 */
#define led9_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define led9_0_INBUF_ENABLED 0u
#define led9_0_INIT_DRIVESTATE 1u
#define led9_0_INIT_MUXSEL 0u
#define led9_0_INPUT_SYNC 2u
#define led9_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define led9_0_NUM 7u
#define led9_0_PORT GPIO_PRT13
#define led9_0_SLEWRATE CY_GPIO_SLEW_FAST
#define led9_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define led9_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define led9_INBUF_ENABLED 0u
#define led9_INIT_DRIVESTATE 1u
#define led9_INIT_MUXSEL 0u
#define led9_INPUT_SYNC 2u
#define led9_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define led9_NUM 7u
#define led9_PORT GPIO_PRT13
#define led9_SLEWRATE CY_GPIO_SLEW_FAST
#define led9_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* green */
#define green_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define green_0_INBUF_ENABLED 0u
#define green_0_INIT_DRIVESTATE 0u
#define green_0_INIT_MUXSEL 0u
#define green_0_INPUT_SYNC 2u
#define green_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define green_0_NUM 1u
#define green_0_PORT GPIO_PRT1
#define green_0_SLEWRATE CY_GPIO_SLEW_FAST
#define green_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define green_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define green_INBUF_ENABLED 0u
#define green_INIT_DRIVESTATE 0u
#define green_INIT_MUXSEL 0u
#define green_INPUT_SYNC 2u
#define green_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define green_NUM 1u
#define green_PORT GPIO_PRT1
#define green_SLEWRATE CY_GPIO_SLEW_FAST
#define green_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 0u
#define UART_1_rx_0_PORT GPIO_PRT5
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 0u
#define UART_1_rx_PORT GPIO_PRT5
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 1u
#define UART_1_tx_0_PORT GPIO_PRT5
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 1u
#define UART_1_tx_PORT GPIO_PRT5
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
