/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* RED */
#define RED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_0_INBUF_ENABLED 0u
#define RED_0_INIT_DRIVESTATE 1u
#define RED_0_INIT_MUXSEL 3u
#define RED_0_INPUT_SYNC 2u
#define RED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_0_NUM 3u
#define RED_0_PORT GPIO_PRT0
#define RED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_INBUF_ENABLED 0u
#define RED_INIT_DRIVESTATE 1u
#define RED_INIT_MUXSEL 3u
#define RED_INPUT_SYNC 2u
#define RED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_NUM 3u
#define RED_PORT GPIO_PRT0
#define RED_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* EZI2C_scl */
#define EZI2C_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define EZI2C_scl_0_INBUF_ENABLED 1u
#define EZI2C_scl_0_INIT_DRIVESTATE 1u
#define EZI2C_scl_0_INIT_MUXSEL 19u
#define EZI2C_scl_0_INPUT_SYNC 2u
#define EZI2C_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define EZI2C_scl_0_NUM 0u
#define EZI2C_scl_0_PORT GPIO_PRT6
#define EZI2C_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define EZI2C_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define EZI2C_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define EZI2C_scl_INBUF_ENABLED 1u
#define EZI2C_scl_INIT_DRIVESTATE 1u
#define EZI2C_scl_INIT_MUXSEL 19u
#define EZI2C_scl_INPUT_SYNC 2u
#define EZI2C_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define EZI2C_scl_NUM 0u
#define EZI2C_scl_PORT GPIO_PRT6
#define EZI2C_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define EZI2C_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* EZI2C_sda */
#define EZI2C_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define EZI2C_sda_0_INBUF_ENABLED 1u
#define EZI2C_sda_0_INIT_DRIVESTATE 1u
#define EZI2C_sda_0_INIT_MUXSEL 19u
#define EZI2C_sda_0_INPUT_SYNC 2u
#define EZI2C_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define EZI2C_sda_0_NUM 1u
#define EZI2C_sda_0_PORT GPIO_PRT6
#define EZI2C_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define EZI2C_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define EZI2C_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define EZI2C_sda_INBUF_ENABLED 1u
#define EZI2C_sda_INIT_DRIVESTATE 1u
#define EZI2C_sda_INIT_MUXSEL 19u
#define EZI2C_sda_INPUT_SYNC 2u
#define EZI2C_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define EZI2C_sda_NUM 1u
#define EZI2C_sda_PORT GPIO_PRT6
#define EZI2C_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define EZI2C_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
