/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* A0 */
#define A0_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define A0_0_INBUF_ENABLED 0u
#define A0_0_INIT_DRIVESTATE 1u
#define A0_0_INIT_MUXSEL 0u
#define A0_0_INPUT_SYNC 2u
#define A0_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define A0_0_NUM 0u
#define A0_0_PORT GPIO_PRT10
#define A0_0_SLEWRATE CY_GPIO_SLEW_FAST
#define A0_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define A0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define A0_INBUF_ENABLED 0u
#define A0_INIT_DRIVESTATE 1u
#define A0_INIT_MUXSEL 0u
#define A0_INPUT_SYNC 2u
#define A0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define A0_NUM 0u
#define A0_PORT GPIO_PRT10
#define A0_SLEWRATE CY_GPIO_SLEW_FAST
#define A0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* A1 */
#define A1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define A1_0_INBUF_ENABLED 0u
#define A1_0_INIT_DRIVESTATE 1u
#define A1_0_INIT_MUXSEL 0u
#define A1_0_INPUT_SYNC 2u
#define A1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define A1_0_NUM 1u
#define A1_0_PORT GPIO_PRT10
#define A1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define A1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define A1_DRIVEMODE CY_GPIO_DM_ANALOG
#define A1_INBUF_ENABLED 0u
#define A1_INIT_DRIVESTATE 1u
#define A1_INIT_MUXSEL 0u
#define A1_INPUT_SYNC 2u
#define A1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define A1_NUM 1u
#define A1_PORT GPIO_PRT10
#define A1_SLEWRATE CY_GPIO_SLEW_FAST
#define A1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* A2 */
#define A2_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define A2_0_INBUF_ENABLED 0u
#define A2_0_INIT_DRIVESTATE 1u
#define A2_0_INIT_MUXSEL 0u
#define A2_0_INPUT_SYNC 2u
#define A2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define A2_0_NUM 2u
#define A2_0_PORT GPIO_PRT10
#define A2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define A2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define A2_DRIVEMODE CY_GPIO_DM_ANALOG
#define A2_INBUF_ENABLED 0u
#define A2_INIT_DRIVESTATE 1u
#define A2_INIT_MUXSEL 0u
#define A2_INPUT_SYNC 2u
#define A2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define A2_NUM 2u
#define A2_PORT GPIO_PRT10
#define A2_SLEWRATE CY_GPIO_SLEW_FAST
#define A2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* A3 */
#define A3_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define A3_0_INBUF_ENABLED 0u
#define A3_0_INIT_DRIVESTATE 0u
#define A3_0_INIT_MUXSEL 0u
#define A3_0_INPUT_SYNC 2u
#define A3_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define A3_0_NUM 3u
#define A3_0_PORT GPIO_PRT10
#define A3_0_SLEWRATE CY_GPIO_SLEW_FAST
#define A3_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define A3_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define A3_INBUF_ENABLED 0u
#define A3_INIT_DRIVESTATE 0u
#define A3_INIT_MUXSEL 0u
#define A3_INPUT_SYNC 2u
#define A3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define A3_NUM 3u
#define A3_PORT GPIO_PRT10
#define A3_SLEWRATE CY_GPIO_SLEW_FAST
#define A3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 0u
#define UART_1_rx_0_PORT GPIO_PRT5
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 0u
#define UART_1_rx_PORT GPIO_PRT5
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 1u
#define UART_1_tx_0_PORT GPIO_PRT5
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 1u
#define UART_1_tx_PORT GPIO_PRT5
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
