/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* RED */
#define RED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_0_INBUF_ENABLED 0u
#define RED_0_INIT_DRIVESTATE 1u
#define RED_0_INIT_MUXSEL 3u
#define RED_0_INPUT_SYNC 2u
#define RED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_0_NUM 3u
#define RED_0_PORT GPIO_PRT0
#define RED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_INBUF_ENABLED 0u
#define RED_INIT_DRIVESTATE 1u
#define RED_INIT_MUXSEL 3u
#define RED_INPUT_SYNC 2u
#define RED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_NUM 3u
#define RED_PORT GPIO_PRT0
#define RED_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* GREEN */
#define GREEN_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GREEN_0_INBUF_ENABLED 0u
#define GREEN_0_INIT_DRIVESTATE 1u
#define GREEN_0_INIT_MUXSEL 3u
#define GREEN_0_INPUT_SYNC 2u
#define GREEN_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GREEN_0_NUM 1u
#define GREEN_0_PORT GPIO_PRT1
#define GREEN_0_SLEWRATE CY_GPIO_SLEW_FAST
#define GREEN_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define GREEN_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GREEN_INBUF_ENABLED 0u
#define GREEN_INIT_DRIVESTATE 1u
#define GREEN_INIT_MUXSEL 3u
#define GREEN_INPUT_SYNC 2u
#define GREEN_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GREEN_NUM 1u
#define GREEN_PORT GPIO_PRT1
#define GREEN_SLEWRATE CY_GPIO_SLEW_FAST
#define GREEN_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 0u
#define UART_1_rx_0_PORT GPIO_PRT5
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 0u
#define UART_1_rx_PORT GPIO_PRT5
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 1u
#define UART_1_tx_0_PORT GPIO_PRT5
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 1u
#define UART_1_tx_PORT GPIO_PRT5
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
